create table STATE(
STATE_ID SERIAL PRIMARY KEY NOT NULL,
NAME VARCHAR(100));

CREATE table COLOR(
COLOR_ID SERIAL PRIMARY KEY NOT NULL,
NAME VARCHAR(50));

create table TEAM(
TEAM_ID SERIAL PRIMARY KEY NOT NULL,
NAME VARCHAR(100),
STATE_ID INT,
COLOR_ID INT,
WINS INT,
LOSSES INT,
FOREIGN KEY (STATE_ID) REFERENCES STATE(STATE_ID) ON DELETE SET NULL ON UPDATE CASCADE);

create table PLAYER(
PLAYER_ID SERIAL PRIMARY KEY NOT NULL, 
TEAM_ID INT,
UNIFORM_NUM INT,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
MPG INT,
PPG INT,
RPG INT,
APG INT,
SPG DEC(4,1),
BPG DEC(4,1),
FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID) ON DELETE SET NULL ON UPDATE CASCADE);



