# Generated by Django 4.0.1 on 2022-03-17 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team_colorID', to='myapp.color')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team_stateID', to='myapp.state')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('uniform_num', models.IntegerField(default=0)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mpg', models.IntegerField(default=0)),
                ('ppg', models.IntegerField(default=0)),
                ('rpg', models.IntegerField(default=0)),
                ('apg', models.IntegerField(default=0)),
                ('spg', models.FloatField()),
                ('bpg', models.FloatField()),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.team')),
            ],
        ),
    ]
